local SoundRegistry = require("WorkingPhones/Registries/PhoneSoundRegistry")

SoundRegistry.registerMany({
	{
		id = "classic_ring_1",
		event = "nokia_tune_type1",
		labelKey = "Sound_ClassicTone1",
		kinds = { "ringtone", "notification", "alarm" },
		packs = { "classic_2110" },
		order = 10,
	},
	{
		id = "classic_pulse",
		event = "nokia_tune_type2",
		labelKey = "Sound_ClassicTone2",
		kinds = { "ringtone", "notification", "alarm" },
		packs = { "classic_2110" },
		order = 20,
	},
	{
		id = "classic_bright",
		event = "nokia_tune_type3",
		labelKey = "Sound_ClassicTone3",
		kinds = { "ringtone", "notification", "alarm" },
		packs = { "classic_2110" },
		order = 30,
	},
	{
		id = "classic_soft",
		event = "nokia_tune_type4",
		labelKey = "Sound_ClassicTone4",
		kinds = { "ringtone", "notification", "alarm" },
		packs = { "classic_2110" },
		order = 40,
	},
	{
		id = "classic_long_alert",
		event = "nokia_tune_type5",
		labelKey = "Sound_ClassicTone5",
		kinds = { "ringtone", "notification", "alarm" },
		packs = { "classic_2110" },
		order = 50,
	},
	{
		id = "classic_digital",
		event = "nokia_tune_type6",
		labelKey = "Sound_ClassicTone6",
		kinds = { "ringtone", "notification", "alarm" },
		packs = { "classic_2110" },
		order = 60,
	},
	{
		id = "classic_short",
		event = "nokia_tune_type7",
		labelKey = "Sound_ClassicTone7",
		kinds = { "ringtone", "notification", "alarm" },
		packs = { "classic_2110" },
		order = 70,
	},
	{
		id = "smartphone_ring_1",
		event = "smartphone_ringtone_1",
		labelKey = "Sound_SmartphoneRing1",
		kind = "ringtone",
		packs = { "generic_smartphone" },
		order = 10,
	},
	{
		id = "smartphone_ring_2",
		event = "smartphone_ringtone_2",
		labelKey = "Sound_SmartphoneRing2",
		kind = "ringtone",
		packs = { "generic_smartphone" },
		order = 20,
	},
	{
		id = "smartphone_ring_3",
		event = "smartphone_ringtone_3",
		labelKey = "Sound_SmartphoneRing3",
		kind = "ringtone",
		packs = { "generic_smartphone" },
		order = 30,
	},
	{
		id = "smartphone_ring_4",
		event = "smartphone_ringtone_4",
		labelKey = "Sound_SmartphoneRing4",
		kind = "ringtone",
		packs = { "generic_smartphone" },
		order = 40,
	},
	{
		id = "smartphone_notification_1",
		event = "smartphone_notification_1",
		labelKey = "Sound_SmartphoneNotification1",
		kind = "notification",
		packs = { "generic_smartphone" },
		order = 10,
	},
	{
		id = "smartphone_notification_2",
		event = "smartphone_notification_2",
		labelKey = "Sound_SmartphoneNotification2",
		kind = "notification",
		packs = { "generic_smartphone" },
		order = 20,
	},
	{
		id = "smartphone_notification_3",
		event = "smartphone_notification_3",
		labelKey = "Sound_SmartphoneNotification3",
		kind = "notification",
		packs = { "generic_smartphone" },
		order = 30,
	},
	{
		id = "smartphone_notification_4",
		event = "smartphone_notification_4",
		labelKey = "Sound_SmartphoneNotification4",
		kind = "notification",
		packs = { "generic_smartphone" },
		order = 40,
	},
	{
		id = "smartphone_notification_5",
		event = "smartphone_notification_5",
		labelKey = "Sound_SmartphoneNotification5",
		kind = "notification",
		packs = { "generic_smartphone" },
		order = 50,
	},
	{
		id = "smartphone_notification_6",
		event = "smartphone_notification_6",
		labelKey = "Sound_SmartphoneNotification6",
		kind = "notification",
		packs = { "generic_smartphone" },
		order = 60,
	},
	{
		id = "smartphone_notification_7",
		event = "smartphone_notification_7",
		labelKey = "Sound_SmartphoneNotification7",
		kind = "notification",
		packs = { "generic_smartphone" },
		order = 70,
	},
	{
		id = "smartphone_alarm_1",
		event = "smartphone_alarm_1",
		labelKey = "Sound_SmartphoneAlarm1",
		kind = "alarm",
		packs = { "generic_smartphone" },
		order = 10,
	},
	{
		id = "smartphone_alarm_2",
		event = "smartphone_alarm_2",
		labelKey = "Sound_SmartphoneAlarm2",
		kind = "alarm",
		packs = { "generic_smartphone" },
		order = 20,
	},
	{
		id = "smartphone_alarm_3",
		event = "smartphone_alarm_3",
		labelKey = "Sound_SmartphoneAlarm3",
		kind = "alarm",
		packs = { "generic_smartphone" },
		order = 30,
	},
	{
		id = "phone_vibrate_short",
		event = "phone_vibrating_short",
		labelKey = "Sound_VibrateShort",
		kind = "vibration",
		packs = { "shared_vibration" },
		order = 10,
	},
	{
		id = "phone_vibrate_long",
		event = "phone_vibrating_long",
		labelKey = "Sound_VibrateLong",
		kind = "vibration",
		packs = { "shared_vibration" },
		order = 20,
	},
})

return SoundRegistry
