local PhoneRegistry = require("WorkingPhones/Core/PhoneRegistry")
local Assets = require("WorkingPhones/Assets/PhoneAssets")

return PhoneRegistry.register({
	id = "classic_2110",
	displayName = "Classic 2210 Phone",
	displayNameKey = "PhoneClassic2210",
	texture = Assets.CLASSIC_2210_BODY .. "ui_working_phones_classic_phone_front_black.png",
	screenRect = { x = 94, y = 525, width = 443, height = 402 },
	theme = "classic_green",
	hardwareType = "classic",
	supportedApps = {
		"calculator",
		"calendar",
		"clock",
		"contacts",
		"games",
		"journal",
		"map",
		"messages",
		"phone",
		"settings",
		"sounds",
	},
	defaultApps = {
		"phone",
		"messages",
		"contacts",
		"clock",
		"calendar",
		"calculator",
		"games",
		"journal",
		"map",
		"sounds",
		"settings",
	},
	inputMode = "keypad",
	soundProfile = {
		soundPacks = { "classic_2110", "shared_vibration" },
		defaultRingtone = "classic_ring_1",
		defaultNotification = "classic_long_alert",
		defaultAlarm = "classic_bright",
		defaultNotificationVibration = "phone_vibrate_short",
		defaultCallVibration = "phone_vibrate_long",
		defaultAlarmVibration = "phone_vibrate_long",
		volume = 0.7,
	},
	osProfile = {
		id = "wp_classic_os",
		colorMode = "monochrome",
	},
	hardware = {
		displayMode = "monochrome",
		touch = false,
		battery = 1.0,
		startsPowered = true,
	},
	panel = {
		scale = 1,
		maxScreenHeightRatio = 0.9,
	},
	buttonOrder = {
		"POWER",
		"LEFT_SOFT",
		"RIGHT_SOFT",
		"UP",
		"DOWN",
		"CLEAR",
		"ABC",
		"KEY_1",
		"KEY_2",
		"KEY_3",
		"KEY_4",
		"KEY_5",
		"KEY_6",
		"KEY_7",
		"KEY_8",
		"KEY_9",
		"KEY_STAR",
		"KEY_0",
		"KEY_HASH",
	},
	buttons = {
		POWER = { x = 507, y = 242, width = 65, height = 82 },
		LEFT_SOFT = { x = 109, y = 991, width = 98, height = 58 },
		RIGHT_SOFT = { x = 421, y = 991, width = 98, height = 58 },
		UP = { x = 249, y = 990, width = 128, height = 41 },
		DOWN = { x = 249, y = 1066, width = 128, height = 41 },
		CLEAR = { x = 56, y = 1056, width = 63, height = 64 },
		ABC = { x = 509, y = 1057, width = 63, height = 64 },
		KEY_1 = { x = 92, y = 1218, width = 124, height = 60, action = "KEYPAD", value = "1" },
		KEY_2 = { x = 248, y = 1218, width = 124, height = 60, action = "KEYPAD", value = "2", letters = "ABC" },
		KEY_3 = { x = 409, y = 1218, width = 124, height = 60, action = "KEYPAD", value = "3", letters = "DEF" },
		KEY_4 = { x = 92, y = 1305, width = 124, height = 60, action = "KEYPAD", value = "4", letters = "GHI" },
		KEY_5 = { x = 248, y = 1305, width = 124, height = 60, action = "KEYPAD", value = "5", letters = "JKL" },
		KEY_6 = { x = 409, y = 1305, width = 124, height = 60, action = "KEYPAD", value = "6", letters = "MN" },
		KEY_7 = { x = 92, y = 1389, width = 124, height = 60, action = "KEYPAD", value = "7", letters = "PRS" },
		KEY_8 = { x = 248, y = 1389, width = 124, height = 60, action = "KEYPAD", value = "8", letters = "TUV" },
		KEY_9 = { x = 409, y = 1389, width = 124, height = 60, action = "KEYPAD", value = "9", letters = "WXY" },
		KEY_STAR = { x = 92, y = 1476, width = 124, height = 60, action = "KEYPAD", value = "*", letters = "+" },
		KEY_0 = { x = 248, y = 1476, width = 124, height = 60, action = "KEYPAD", value = "0", letters = "OQZ" },
		KEY_HASH = { x = 409, y = 1476, width = 124, height = 60, action = "KEYPAD", value = "#" },
	},
})
