local PhoneRegistry = require("WorkingPhones/Core/PhoneRegistry")
local Assets = require("WorkingPhones/Assets/PhoneAssets")

return PhoneRegistry.register({
	id = "classic_2110",
	displayName = "Classic 2210 Phone",
	displayNameKey = "PhoneClassic2210",
	texture = Assets.CLASSIC_2210_BODY .. "ui_working_phones_classic_phone_front.png",
	screenRect = { x = 60, y = 335, width = 272, height = 225 },
	theme = "classic_green",
	hardwareType = "classic",
	supportedApps = {
		"calculator",
		"calendar",
		"clock",
		"contacts",
		"games",
		"journal",
		"map",
		"messages",
		"phone",
		"settings",
		"sounds",
	},
	defaultApps = {
		"phone",
		"messages",
		"contacts",
		"clock",
		"calendar",
		"calculator",
		"games",
		"journal",
		"map",
		"sounds",
		"settings",
	},
	inputMode = "keypad",
	soundProfile = {
		soundPacks = { "classic_2110", "shared_vibration" },
		defaultRingtone = "classic_ring_1",
		defaultNotification = "classic_long_alert",
		defaultAlarm = "classic_bright",
		defaultNotificationVibration = "phone_vibrate_short",
		defaultCallVibration = "phone_vibrate_long",
		defaultAlarmVibration = "phone_vibrate_long",
		volume = 0.7,
	},
	osProfile = {
		id = "wp_classic_os",
		colorMode = "monochrome",
	},
	hardware = {
		displayMode = "monochrome",
		touch = false,
		battery = 1.0,
		startsPowered = true,
	},
	panel = {
		scale = 1,
		maxScreenHeightRatio = 0.9,
	},
	buttons = {
		MENU = { x = 70, y = 580, width = 80, height = 58 },
		BACK = { x = 230, y = 580, width = 80, height = 58 },
		OK = { x = 150, y = 630, width = 80, height = 58 },
		UP = { x = 158, y = 560, width = 64, height = 46 },
		DOWN = { x = 158, y = 692, width = 64, height = 46 },
		LEFT = { x = 100, y = 626, width = 56, height = 52 },
		RIGHT = { x = 224, y = 626, width = 56, height = 52 },
		POWER = { x = 245, y = 750, width = 68, height = 42 },
	},
})
